Improve CI permissions and fix Java for JRuby 10
Workflows run with extended set of permissions by default.
By specifying any permission explicitly, all others are set to none.

Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

JRuby 10.0 Requires Java 21 but Java 17 was used. This eliminates the following
error:

```
Error: LinkageError occurred while loading main class org.jruby.Main
java.lang.UnsupportedClassVersionError: org/jruby/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
JRuby failed to start, try Java 21 envs
```